services:
  web_app:
    build: .
    image: etickets
    container_name: etickets_web_app
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: "mysql"
    container_name: eTicketsDB
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "etickets"
      MYSQL_USER: user1
      MYSQL_PASSWORD: Taska189*
      MYSQL_ROOT_PASSWORD: Taska189*